/*
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.mmmi.TypescriptdslRuntimeModule;
import dk.sdu.mmmi.TypescriptdslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TypescriptdslIdeSetup extends TypescriptdslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TypescriptdslRuntimeModule(), new TypescriptdslIdeModule()));
	}
	
}
