/*
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TypescriptdslStandaloneSetup extends TypescriptdslStandaloneSetupGenerated {

	public static void doSetup() {
		new TypescriptdslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
