/*
 * generated by Xtext 2.24.0
 */
package dk.sdu.mmmi.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TypescriptdslUiModule extends AbstractTypescriptdslUiModule {

	public TypescriptdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
